### ISSUE TITLE
 go get github.com/docker/distribution/cmd/registry is showing errors with go version 1.4.2

### ISSUE THREAD

**Issue by mathewkoshy493** [stevvooe/resumable#3]
When I am trying to get docker registry using go get github.com/docker/distribution/cmd/registry,the following error is coming.My go version is 1.4.2.When i updated my golang to 1.5 the problem is solved
# github.com/stevvooe/resumable/sha512

github.com/stevvooe/resumable/sha512/resume.go:56: undefined: crypto.SHA512_224
github.com/stevvooe/resumable/sha512/resume.go:56: undefined: crypto.SHA512_256
github.com/stevvooe/resumable/sha512/sha512.go:17: undefined: crypto.SHA512_224
github.com/stevvooe/resumable/sha512/sha512.go:18: undefined: crypto.SHA512_256
github.com/stevvooe/resumable/sha512/sha512.go:95: undefined: crypto.SHA512_224
github.com/stevvooe/resumable/sha512/sha512.go:104: undefined: crypto.SHA512_256
github.com/stevvooe/resumable/sha512/sha512.go:136: undefined: crypto.SHA512_224
github.com/stevvooe/resumable/sha512/sha512.go:143: undefined: crypto.SHA512_256
github.com/stevvooe/resumable/sha512/sha512.go:157: undefined: crypto.SHA512_224
github.com/stevvooe/resumable/sha512/sha512.go:159: undefined: crypto.SHA512_256
github.com/stevvooe/resumable/sha512/sha512.go:159: too many errors

**Comment by stevvooe** [comment]
@mathewkoshy493 This package is only supported for go1.5 and higher.

**Comment by stevvooe** [comment]
@mathewkoshy493 I think I can tag the repository to use the old version of the package for go1.4. Could you find the last working version?

**Comment by murdegern** [comment]
Just git bisected it with go 1.4.2 from Scientific Linux 7 current; the last working commit is
51ad44105773cafcbe91927f70ac68e1bf78f8b4

**Comment by stevvooe** [comment]
@murdegern Thank you.

After some research, it seems [only the "go1" tag is supported](https://golang.org/src/cmd/go/get.go#L476), for now. I'll have to fix this with some careful build tags.

How long do you expect to be on Go 1.4? It may be enough to tag that revision and include a note in the README.

**Comment by stevvooe** [comment]
@murdegern At this time, I'm not sure Go 1.4 is still a valid target. Closing this issue.
